name: Cron
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-invoices:
    runs-on: ubuntu-latest
    steps:
      - name: Call the Vercel app to update invoices
        run: curl -X POST https://my-vercel-app.vercel.app/api/update-invoices
